### PR TITLE
BA-488: Refactor navigation menu

### PR DESCRIPTION
**Pull request by JacobMu**
JIRA ticket: https://inovaciebratislava.atlassian.net/browse/BA-488

Sorry for the size 😢 
This PR refactored navigation menu (homepage and sticky menus) to not rely too much on `:hover` and rather use states to render different states of menu items.

### CODE REVIEW

**Comment by Balros** [comment]
I lost background in whole homepage.
image

**Comment by Balros** [comment]
When i click on search icon site can't be scrolled

**Comment by Balros** [comment]
sticky menu width is bigger then content

**Comment by Balros** [comment]
when i click on search icon, it scrolls the page to top

**Comment by Balros** [comment]
grey overlay on opened menu is missing

**Comment by Balros** [comment]
sticky menu has bigger height then it had

**Comment by Balros** [comment]
clicking outside of opened menu will not close it when cookies consent is showing

**Comment by Balros** [comment]
- menu items is not on full width of available space
- page can be moved left/right - we don't want that
Screenshot 2022-10-19 at 17 17 56

**Comment by JacobMu** [comment]
I am going to close this PR. It is far too big for a quality review. I am implementing the refactoring in phases to have smaller PRs that are easy to read and understand + there won't be need for rebasing too often.

**Pull request closed without merging**
