### PR TITLE
Form-187 basic style + changed wording in Alert showcase (not finished)

### PR DESCRIPTION
**Pull request by AkihitoVM**

### CODE REVIEW

**Review by mpinter — APPROVED** [review]
Fine as a visual showcase, please fix the following hover button color & we can merge:

Screenshot 2022-10-31 at 16 22 19

Note though that as part of FORM-187, we expect a functioning modal component in the styleguide - so I've moved the task to In progress, and please move it forward only once there's a PR with modal with proper modal props - controlling opening, closing as well as the content, headers, actions and texts on buttons etc. The `flow` prop will probably want to work differently as well. Styleguide should showcase the modal being openable, dismissable, and "steppable over" in case of the modal with an arrow.

**Comment by AkihitoVM** [comment]
now it works correctly as a normal modal window, but still don't understand what about content type, will be discussed on standup

**Review by mpinter — CHANGES_REQUESTED** [review]
Please fix so that it does not contain changes not related to this PR.

When the Modal is put together, it shouldn't contain the divider gray lines lines, should be in "one piece".

Screenshot 2022-11-03 at 11 15 00

Will take a look at the code once more when it contains just the relevant changes.

**Comment by AkihitoVM** [comment]
> 

I did what was in figma, idk ( gray lines )
image


"changes not related to this PR." - you mean screens (first,second,third) for testing or what?

**Review by mpinter — APPROVED** [review]
Changes not in PR - no, what I've ment are most likely git conflicts, like if you look at "commits" tab on github pullrequest you'll see the commit "FORM-192 text and html transform" being part of this PR, which it shouldn't be.

Please clean up as part of solving all the other conflicts as well.

As to the gray lines - I'm checking with Patrik in [this message](https://inovaciebratislava.slack.com/archives/C0458KY6YG1/p1668404621613089), please wait for the reply there and if need be, change accordingly. Once that is answered and resolved, you can merge without further review.

**Pull request closed without merging**
