### PR TITLE
BA-745: Adjust event component design

### PR DESCRIPTION
**Pull request by JacobMu**
[JIRA task](https://inovaciebratislava.atlassian.net/browse/BA-745)

image

### CODE REVIEW

**Review by mpinter — CHANGES_REQUESTED** [review]
for some reason still does not look right, at least on Safari:

Screenshot 2023-01-27 at 10 00 47

I don't believe the img component you were changing has effect on this

**Comment by JacobMu** [comment]
@mpinter 
should be fixed now. It looks like safari did interpret styles differently than Chrome or Firefox.

**Review by mpinter — APPROVED** [review]
:+1: looks good, thanks!

**Comment by radoslavzeman** [comment]
Outdated.

**Pull request closed without merging**
