### PR TITLE
Form-343/Fix_Tailwindcss_bugs

### PR DESCRIPTION
**Pull request by ValeriiMedvezhonkov**
Fix alert css, fix icons from figma

### CODE REVIEW

**Comment by mpinter** [comment]
@AntonZezul can you please take a look at this - if it looks good to you and resolves all the issues you know of go ahead and merge

**Comment by AntonZezul** [comment]
All fields components doesn't have red border when have error state
You can delete log in InputField.tsx:152 in this PR
Then we can 🚢

**Comment by ValeriiMedvezhonkov** [comment]
@mpinter issue was fixed, please approve to merge

**Review by mpinter — APPROVED** [review]
lgtm

**Pull request merged**
